<?php
	require('core/common.php');
	require('core/constants.php');
	require('core/registry.php');
	require('core/loader.php');
	require('core/request.php');
	require('core/response.php');
	require('core/router.php');
	require('core/controller.php');
	require('core/model.php');
	require('database/database.php');
 ?>